### ISSUE TITLE
Generated Object not Generating after Baking to Alembic Stream

### ISSUE THREAD

**Issue by TomasCalinaoCorrea** [snorulf/FlipBookMeshBaker#1]
Im trying to convert a simple alembic animation but no new Gameobject is being generated. I continually get the following console error when trying to bake. 

UnityException: Creating asset at path \Assets\BakeFolder_0.asset failed.
BakeFlipBookMeshEditor.BakeAlembic (System.String meshName, System.String filepath, System.Single alembicStepSize) (at Assets/FlipBookMeshBaker-main/Assets/MeshBaking/Editor/BakeFlipBookMeshEditor.cs:93)
BakeFlipBookMeshEditor.OnGUI () (at Assets/FlipBookMeshBaker-main/Assets/MeshBaking/Editor/BakeFlipBookMeshEditor.cs:42)

Is there something I'm missing? I tried deleting the sample flip book with the car but it did not help. Really looking to use this on android so any help would be greatly appreciated!

**Comment by snorulf** [comment]
Make sure the path defined in 'Output' exists in your project and that you
have provided a name for your asset in it.

Something like 'Assets\MyFlipBookMesh' should work for example.

Also you need to make sure the folder is not occupied by files of the same
asset name I guess.

Den fre 26 juli 2024 04:45TomasCalinaoCorrea ***@***.***>
skrev:

**Comment by TomasCalinaoCorrea** [comment]
Yes got it to work now thank you. I think the default output set initially when first setting up could be optimized. Would help if it was set to an already empty folder, as well as written correctly as I believe the notation of the slashes was incorrect. Now that it is working though it works well so thank you so much for this tool!

**Comment by snorulf** [comment]
Good to hear, hope you find some use for it. And thanks for the feedback.
