### ISSUE TITLE
Error when create mesh assets

### ISSUE THREAD

**Issue by Karim-Sheetos2269** [snorulf/FlipBookMeshBaker#2]
Hello, first of all
I would like to congratulate you on this wonderful work.
I have a problem please , I did all the steps as shown in the video but it did not work well what is the reason please?
Video : https://drive.google.com/file/d/1T5sfLkBFmFDTbFgRSklAMQK2pW_E9s8l/view?usp=sharing
Thank you very much

**Comment by snorulf** [comment]
Hello,
Ok, that looks strange. Are you able to share the model so I can have a look at what is going on?
Cheers

**Comment by Karim-Sheetos2269** [comment]
Hello , 
this is link : https://drive.google.com/file/d/19Soa592v6trsG2pHi55SCWosmf345qxB/view?usp=sharing

**Comment by snorulf** [comment]
Thanks, I'll have a look in the next few days.

**Comment by snorulf** [comment]
Hi Karim,
Your Alembic contained multiple objects and bake logic would only handle one, it supports multiple objects now. I tested it with your data and it seems to work fine now. Let me know if you find any further issues.
Cheers
